set nocompatible " do not use vi compatible mode

" enable pathogen
source ~/.vim/bundle/vim-pathogen/autoload/pathogen.vim
call pathogen#infect()


filetype plugin indent on " enable filetype checking, plugins and indention
"set omnifunc=syntaxcomplete#Complete
set hlsearch incsearch " highlights all patterns matching search
set ruler " show line/column number
set title " show the title in window
set autochdir " open files relative to directory of currently open file
"set scrolloff=5 " keep at least 5 lines below cursor
set wildmode=longest:full
set wildmenu
"set backspace=indent,eol,start
"set foldlevelstart=99


" saves and switches to next file for editing
map B :w<CR>:bnext<CR>
" map m(M) to next(prev) error in quickfix
map m :cn<CR>zv
map M :cp<CR>zv
" map <leader> m(M) to next(prev) location in location list
map ,m :lnext<CR>zv
map ,M :lprev<CR>zv
" navigate between screen splits
map ,h <C-W>h
map ,l <C-W>l
map ,j <C-W>j
map ,k <C-W>k
" fold with \f, update folds with \F
map <Leader>f za
map <Leader>F zx
" Toggle line numbers with <F2>
nnoremap <F2> :set nonumber!<CR>:set foldcolumn=0<CR>

" Set colorscheme
syntax enable
set background=dark
let g:solarized_termcolors=256
let g:solarized_termtrans = 1
colo solarized
" change colorscheme for vimdiff
"set verbose=9
if &diff | colo shobogenzo | colo solarized | endif
autocmd FilterWritePre * if &diff | colo shobogenzo | else | colo solarized | endif
autocmd FilterWritePost * if &diff | colo shobogenzo | else | colo solarized | endif
"autocmd BufWinLeave * colo solarized



" Configure plugins
let g:EnhCommentifyBindInInsert = 'N'
let g:localvimrc_ask = 0
"
let g:go_def_mode='gopls'
let g:go_info_mode='gopls'

let g:ale_completion_enabled = 1
let g:ale_fixers = {
\  '*': ['remove_trailing_lines', 'trim_whitespace'],
\  'cpp': ['clang-format'],
\  'go': ['gofmt'],
\}
let g:ale_fix_on_save = 1
set omnifunc=ale#completion#OmniFunc
