export EDITOR=vim
export TEXMFLOCAL="$HOME/doc/latex_files/texmf"

alias ls="ls --color"
alias grep="grep --color"

source $HOME/doc/dotfiles/bash/git-completion.bash
PS1='\h:\W$(__git_ps1 "(%s)") \u\$ '
