export EDITOR=vim

if [ -n "${SYS_TYPE}" ] ; then
    if [ "$SYS_TYPE" == "macos" ] ; then
        export CLICOLOR=1
        export LSCOLORS=gxfxbEaEBxxEhEhBaDaCaD
        alias grep="grep --color"
    else
        # needs GNU ls
        DIR=`dirname $BASH_SOURCE`
        eval `dircolors $DIR/dircolors.ansi-dark`
        alias ls="ls --color=tty"
        alias grep="grep --color"
    fi
else
    echo "SYS_TYPE not set"
fi

source "$HOME"/src/dotfiles/bash/git-completion.bash
source "$HOME"/src/dotfiles/bash/pip-completion.bash
#PS1='\h:\W$(__git_ps1 "(%s)") \u\$ '
